services:
  - type: web
    name: robofriends
    env: node
    region: oregon
    plan: free
    installCommand: npm install
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 10000
    envVars:
      - key: NODE_VERSION
        value: 18.18.0

